package tk.zielony.randomdata.place;

public class Country {
    public Country[] countries = {
            new Country("Afghanistan", "93", "AF", "AFG"),
            new Country("Albania", "355", "AL", "ALB"),
            new Country("Algeria", "213", "DZ", "DZA"),
            new Country("American Samoa", "1-684", "AS", "ASM"),
            new Country("Andorra", "376", "AD", "AND"),
            new Country("Angola", "244", "AO", "AGO"),
            new Country("Anguilla", "1-264", "AI", "AIA"),
            new Country("Antarctica", "672", "AQ", "ATA"),
            new Country("Antigua and Barbuda", "1-268", "AG", "ATG"),
            new Country("Argentina", "54", "AR", "ARG"),
            new Country("Armenia", "374", "AM", "ARM"),
            new Country("Aruba", "297", "AW", "ABW"),
            new Country("Australia", "61", "AU", "AUS"),
            new Country("Austria", "43", "AT", "AUT"),
            new Country("Azerbaijan", "994", "AZ", "AZE"),
            new Country("Bahamas", "1-242", "BS", "BHS"),
            new Country("Bahrain", "973", "BH", "BHR"),
            new Country("Bangladesh", "880", "BD", "BGD"),
            new Country("Barbados", "1-246", "BB", "BRB"),
            new Country("Belarus", "375", "BY", "BLR"),
            new Country("Belgium", "32", "BE", "BEL"),
            new Country("Belize", "501", "BZ", "BLZ"),
            new Country("Benin", "229", "BJ", "BEN"),
            new Country("Bermuda", "1-441", "BM", "BMU"),
            new Country("Bhutan", "975", "BT", "BTN"),
            new Country("Bolivia", "591", "BO", "BOL"),
            new Country("Bosnia and Herzegovina", "387", "BA", "BIH"),
            new Country("Botswana", "267", "BW", "BWA"),
            new Country("Brazil", "55", "BR", "BRA"),
            new Country("British Indian Ocean Territory", "246", "IO", "IOT"),
            new Country("British Virgin Islands", "1-284", "VG", "VGB"),
            new Country("Brunei", "673", "BN", "BRN"),
            new Country("Bulgaria", "359", "BG", "BGR"),
            new Country("Burkina Faso", "226", "BF", "BFA"),
            new Country("Burundi", "257", "BI", "BDI"),
            new Country("Cambodia", "855", "KH", "KHM"),
            new Country("Cameroon", "237", "CM", "CMR"),
            new Country("Canada", "1", "CA", "CAN"),
            new Country("Cape Verde", "238", "CV", "CPV"),
            new Country("Cayman Islands", "1-345", "KY", "CYM"),
            new Country("Central African Republic", "236", "CF", "CAF"),
            new Country("Chad", "235", "TD", "TCD"),
            new Country("Chile", "56", "CL", "CHL"),
            new Country("China", "86", "CN", "CHN"),
            new Country("Christmas Island", "61", "CX", "CXR"),
            new Country("Cocos Islands", "61", "CC", "CCK"),
            new Country("Colombia", "57", "CO", "COL"),
            new Country("Comoros", "269", "KM", "COM"),
            new Country("Cook Islands", "682", "CK", "COK"),
            new Country("Costa Rica", "506", "CR", "CRI"),
            new Country("Croatia", "385", "HR", "HRV"),
            new Country("Cuba", "53", "CU", "CUB"),
            new Country("Curacao", "599", "CW", "CUW"),
            new Country("Cyprus", "357", "CY", "CYP"),
            new Country("Czech Republic", "420", "CZ", "CZE"),
            new Country("Democratic Republic of the Congo", "243", "CD", "COD"),
            new Country("Denmark", "45", "DK", "DNK"),
            new Country("Djibouti", "253", "DJ", "DJI"),
            new Country("Dominica", "1-767", "DM", "DMA"),
            new Country("Dominican Republic", "1-809, 1-829, 1-849", "DO", "DOM"),
            new Country("East Timor", "670", "TL", "TLS"),
            new Country("Ecuador", "593", "EC", "ECU"),
            new Country("Egypt", "20", "EG", "EGY"),
            new Country("El Salvador", "503", "SV", "SLV"),
            new Country("Equatorial Guinea", "240", "GQ", "GNQ"),
            new Country("Eritrea", "291", "ER", "ERI"),
            new Country("Estonia", "372", "EE", "EST"),
            new Country("Ethiopia", "251", "ET", "ETH"),
            new Country("Falkland Islands", "500", "FK", "FLK"),
            new Country("Faroe Islands", "298", "FO", "FRO"),
            new Country("Fiji", "679", "FJ", "FJI"),
            new Country("Finland", "358", "FI", "FIN"),
            new Country("France", "33", "FR", "FRA"),
            new Country("French Polynesia", "689", "PF", "PYF"),
            new Country("Gabon", "241", "GA", "GAB"),
            new Country("Gambia", "220", "GM", "GMB"),
            new Country("Georgia", "995", "GE", "GEO"),
            new Country("Germany", "49", "DE", "DEU"),
            new Country("Ghana", "233", "GH", "GHA"),
            new Country("Gibraltar", "350", "GI", "GIB"),
            new Country("Greece", "30", "GR", "GRC"),
            new Country("Greenland", "299", "GL", "GRL"),
            new Country("Grenada", "1-473", "GD", "GRD"),
            new Country("Guam", "1-671", "GU", "GUM"),
            new Country("Guatemala", "502", "GT", "GTM"),
            new Country("Guernsey", "44-1481", "GG", "GGY"),
            new Country("Guinea", "224", "GN", "GIN"),
            new Country("Guinea-Bissau", "245", "GW", "GNB"),
            new Country("Guyana", "592", "GY", "GUY"),
            new Country("Haiti", "509", "HT", "HTI"),
            new Country("Honduras", "504", "HN", "HND"),
            new Country("Hong Kong", "852", "HK", "HKG"),
            new Country("Hungary", "36", "HU", "HUN"),
            new Country("Iceland", "354", "IS", "ISL"),
            new Country("India", "91", "IN", "IND"),
            new Country("Indonesia", "62", "ID", "IDN"),
            new Country("Iran", "98", "IR", "IRN"),
            new Country("Iraq", "964", "IQ", "IRQ"),
            new Country("Ireland", "353", "IE", "IRL"),
            new Country("Isle of Man", "44-1624", "IM", "IMN"),
            new Country("Israel", "972", "IL", "ISR"),
            new Country("Italy", "39", "IT", "ITA"),
            new Country("Ivory Coast", "225", "CI", "CIV"),
            new Country("Jamaica", "1-876", "JM", "JAM"),
            new Country("Japan", "81", "JP", "JPN"),
            new Country("Jersey", "44-1534", "JE", "JEY"),
            new Country("Jordan", "962", "JO", "JOR"),
            new Country("Kazakhstan", "7", "KZ", "KAZ"),
            new Country("Kenya", "254", "KE", "KEN"),
            new Country("Kiribati", "686", "KI", "KIR"),
            new Country("Kosovo", "383", "XK", "XKX"),
            new Country("Kuwait", "965", "KW", "KWT"),
            new Country("Kyrgyzstan", "996", "KG", "KGZ"),
            new Country("Laos", "856", "LA", "LAO"),
            new Country("Latvia", "371", "LV", "LVA"),
            new Country("Lebanon", "961", "LB", "LBN"),
            new Country("Lesotho", "266", "LS", "LSO"),
            new Country("Liberia", "231", "LR", "LBR"),
            new Country("Libya", "218", "LY", "LBY"),
            new Country("Liechtenstein", "423", "LI", "LIE"),
            new Country("Lithuania", "370", "LT", "LTU"),
            new Country("Luxembourg", "352", "LU", "LUX"),
            new Country("Macau", "853", "MO", "MAC"),
            new Country("Macedonia", "389", "MK", "MKD"),
            new Country("Madagascar", "261", "MG", "MDG"),
            new Country("Malawi", "265", "MW", "MWI"),
            new Country("Malaysia", "60", "MY", "MYS"),
            new Country("Maldives", "960", "MV", "MDV"),
            new Country("Mali", "223", "ML", "MLI"),
            new Country("Malta", "356", "MT", "MLT"),
            new Country("Marshall Islands", "692", "MH", "MHL"),
            new Country("Mauritania", "222", "MR", "MRT"),
            new Country("Mauritius", "230", "MU", "MUS"),
            new Country("Mayotte", "262", "YT", "MYT"),
            new Country("Mexico", "52", "MX", "MEX"),
            new Country("Micronesia", "691", "FM", "FSM"),
            new Country("Moldova", "373", "MD", "MDA"),
            new Country("Monaco", "377", "MC", "MCO"),
            new Country("Mongolia", "976", "MN", "MNG"),
            new Country("Montenegro", "382", "ME", "MNE"),
            new Country("Montserrat", "1-664", "MS", "MSR"),
            new Country("Morocco", "212", "MA", "MAR"),
            new Country("Mozambique", "258", "MZ", "MOZ"),
            new Country("Myanmar", "95", "MM", "MMR"),
            new Country("Namibia", "264", "NA", "NAM"),
            new Country("Nauru", "674", "NR", "NRU"),
            new Country("Nepal", "977", "NP", "NPL"),
            new Country("Netherlands", "31", "NL", "NLD"),
            new Country("Netherlands Antilles", "599", "AN", "ANT"),
            new Country("New Caledonia", "687", "NC", "NCL"),
            new Country("New Zealand", "64", "NZ", "NZL"),
            new Country("Nicaragua", "505", "NI", "NIC"),
            new Country("Niger", "227", "NE", "NER"),
            new Country("Nigeria", "234", "NG", "NGA"),
            new Country("Niue", "683", "NU", "NIU"),
            new Country("North Korea", "850", "KP", "PRK"),
            new Country("Northern Mariana Islands", "1-670", "MP", "MNP"),
            new Country("Norway", "47", "NO", "NOR"),
            new Country("Oman", "968", "OM", "OMN"),
            new Country("Pakistan", "92", "PK", "PAK"),
            new Country("Palau", "680", "PW", "PLW"),
            new Country("Palestine", "970", "PS", "PSE"),
            new Country("Panama", "507", "PA", "PAN"),
            new Country("Papua New Guinea", "675", "PG", "PNG"),
            new Country("Paraguay", "595", "PY", "PRY"),
            new Country("Peru", "51", "PE", "PER"),
            new Country("Philippines", "63", "PH", "PHL"),
            new Country("Pitcairn", "64", "PN", "PCN"),
            new Country("Poland", "48", "PL", "POL"),
            new Country("Portugal", "351", "PT", "PRT"),
            new Country("Puerto Rico", "1-787, 1-939", "PR", "PRI"),
            new Country("Qatar", "974", "QA", "QAT"),
            new Country("Republic of the Congo", "242", "CG", "COG"),
            new Country("Reunion", "262", "RE", "REU"),
            new Country("Romania", "40", "RO", "ROU"),
            new Country("Russia", "7", "RU", "RUS"),
            new Country("Rwanda", "250", "RW", "RWA"),
            new Country("Saint Barthelemy", "590", "BL", "BLM"),
            new Country("Saint Helena", "290", "SH", "SHN"),
            new Country("Saint Kitts and Nevis", "1-869", "KN", "KNA"),
            new Country("Saint Lucia", "1-758", "LC", "LCA"),
            new Country("Saint Martin", "590", "MF", "MAF"),
            new Country("Saint Pierre and Miquelon", "508", "PM", "SPM"),
            new Country("Saint Vincent and the Grenadines", "1-784", "VC", "VCT"),
            new Country("Samoa", "685", "WS", "WSM"),
            new Country("San Marino", "378", "SM", "SMR"),
            new Country("Sao Tome and Principe", "239", "ST", "STP"),
            new Country("Saudi Arabia", "966", "SA", "SAU"),
            new Country("Senegal", "221", "SN", "SEN"),
            new Country("Serbia", "381", "RS", "SRB"),
            new Country("Seychelles", "248", "SC", "SYC"),
            new Country("Sierra Leone", "232", "SL", "SLE"),
            new Country("Singapore", "65", "SG", "SGP"),
            new Country("Sint Maarten", "1-721", "SX", "SXM"),
            new Country("Slovakia", "421", "SK", "SVK"),
            new Country("Slovenia", "386", "SI", "SVN"),
            new Country("Solomon Islands", "677", "SB", "SLB"),
            new Country("Somalia", "252", "SO", "SOM"),
            new Country("South Africa", "27", "ZA", "ZAF"),
            new Country("South Korea", "82", "KR", "KOR"),
            new Country("South Sudan", "211", "SS", "SSD"),
            new Country("Spain", "34", "ES", "ESP"),
            new Country("Sri Lanka", "94", "LK", "LKA"),
            new Country("Sudan", "249", "SD", "SDN"),
            new Country("Suriname", "597", "SR", "SUR"),
            new Country("Svalbard and Jan Mayen", "47", "SJ", "SJM"),
            new Country("Swaziland", "268", "SZ", "SWZ"),
            new Country("Sweden", "46", "SE", "SWE"),
            new Country("Switzerland", "41", "CH", "CHE"),
            new Country("Syria", "963", "SY", "SYR"),
            new Country("Taiwan", "886", "TW", "TWN"),
            new Country("Tajikistan", "992", "TJ", "TJK"),
            new Country("Tanzania", "255", "TZ", "TZA"),
            new Country("Thailand", "66", "TH", "THA"),
            new Country("Togo", "228", "TG", "TGO"),
            new Country("Tokelau", "690", "TK", "TKL"),
            new Country("Tonga", "676", "TO", "TON"),
            new Country("Trinidad and Tobago", "1-868", "TT", "TTO"),
            new Country("Tunisia", "216", "TN", "TUN"),
            new Country("Turkey", "90", "TR", "TUR"),
            new Country("Turkmenistan", "993", "TM", "TKM"),
            new Country("Turks and Caicos Islands", "1-649", "TC", "TCA"),
            new Country("Tuvalu", "688", "TV", "TUV"),
            new Country("U.S. Virgin Islands", "1-340", "VI", "VIR"),
            new Country("Uganda", "256", "UG", "UGA"),
            new Country("Ukraine", "380", "UA", "UKR"),
            new Country("United Arab Emirates", "971", "AE", "ARE"),
            new Country("United Kingdom", "44", "GB", "GBR"),
            new Country("United States", "1", "US", "USA"),
            new Country("Uruguay", "598", "UY", "URY"),
            new Country("Uzbekistan", "998", "UZ", "UZB"),
            new Country("Vanuatu", "678", "VU", "VUT"),
            new Country("Vatican", "379", "VA", "VAT"),
            new Country("Venezuela", "58", "VE", "VEN"),
            new Country("Vietnam", "84", "VN", "VNM"),
            new Country("Wallis and Futuna", "681", "WF", "WLF"),
            new Country("Western Sahara", "212", "EH", "ESH"),
            new Country("Yemen", "967", "YE", "YEM"),
            new Country("Zambia", "260", "ZM", "ZMB"),
            new Country("Zimbabwe", "263", "ZW", "ZWE")
    };

    private final String name;
    private final String phone;
    private final String code;
    private final String code2;

    private Country(String name, String phone, String code, String code2) {
        this.name = name;
        this.phone = phone;
        this.code = code;
        this.code2 = code2;
    }

    public String getName() {
        return name;
    }

    public String getPhone() {
        return phone;
    }

    public String getCode() {
        return code;
    }

    public String getCode2() {
        return code2;
    }
}
